name: tennis_game_example
description: A [Tennis kata](http://www.codingdojo.org/cgi-bin/index.pl?KataTennis) example.

dependencies:
  sealed_unions: ^2.0.0

dependency_overrides:
  sealed_unions:
    path: ../

environment:
  sdk: '>=1.24.0 <2.0.0'

dev_dependencies:
  test: "^0.12.4+5"